#APPLICATION BROWSER
browser=chrome
#APPLICATION URL
url=https://www.demoblaze.com/index.html
#APPLICATION LOGIN CREDENTIALS
username=TharaniPrabhu
password=Tharz@123
//SCREENSHOTPATH
ScreenshotPath=./screenshots/